
const word = ["Abuse",
    "Adult",
    "Agent",
    "Anger",
    "Apple",
    "Award",
    "Basis",
    "Beach",
    "Birth",
    "Block",
    "Blood",
    "Board",
    "Brain",
    "Bread",
    "Break",
    "Brown",
    "Buyer",
    "Cause",
    "Chain",
    "Chair",
    "Chest",
    "Chief",
    "Child",
    "China",
    "Claim",
    "Class",
    "Clock",
    "Coach",
    "Coast",
    "Court",
    "Cover",
    "Cream",
    "Crime",
    "Cross",
    "Crowd",
    "Crown",
    "Cycle",
    "Dance",
    "Death",
    "Depth",
    "Doubt",
    "Draft",
    "Drama",
    "Dream",
    "Dress",
    "Drink",
    "Drive",
    "Earth",
    "Enemy",
    "Entry",
    "Error",
    "Event",
    "Faith",
    "Fault",
    "Field",
    "Fight",
    "Final",
    "Floor",
    "Focus",
    "Force",
    "Frame",
    "Frank",
    "Front",
    "Fruit",
    "Glass",
    "Grant",
    "Grass",
    "Green",
    "Group",
    "Guide",
    "Heart",
    "Henry",
    "Horse",
    "Hotel",
    "House",
    "Image",
    "Index",
    "Input",
    "Issue",
    "Japan",
    "Jones",
    "Judge",
    "Knife",
    "Laura",
    "Layer",
    "Level",
    "Lewis",
    "Light",
    "Limit",
    "Lunch",
    "Major",
    "March",
    "Match",
    "Metal",
    "Model",
    "Money",
    "Month",
    "Motor",
    "Mouth",
    "Music",
    "Night",
    "Noise",
    "North",
    "Novel",
    "Nurse",
    "Offer",
    "Order",
    "Other",
    "Owner",
    "Panel",
    "Paper",
    "Party",
    "Peace",
    "Peter",
    "Phase",
    "Phone",
    "Piece",
    "Pilot",
    "Pitch",
    "Place",
    "Plane",
    "Plant",
    "Plate",
    "Point",
    "Pound",
    "Power",
    "Press",
    "Price",
    "Pride",
    "Prize",
    "Proof",
    "Queen",
    "Radio",
    "Range",
    "Ratio",
    "Reply",
    "Right",
    "River",
    "Round",
    "Route",
    "Rugby",
    "Scale",
    "Scene",
    "Scope",
    "Score",
    "Sense",
    "Shape",
    "Share",
    "Sheep",
    "Sheet",
    "Shift",
    "Shirt",
    "Shock",
    "Sight",
    "Simon",
    "Skill",
    "Sleep",
    "Smile",
    "Smith",
    "Smoke",
    "Sound",
    "South",
    "Space",
    "Speed",
    "Spite",
    "Sport",
    "Squad",
    "Staff",
    "Stage",
    "Start",
    "State",
    "Steam",
    "Steel",
    "Stock",
    "Stone",
    "Store",
    "Study",
    "Stuff",
    "Style",
    "Sugar",
    "Table",
    "Taste",
    "Terry",
    "Theme",
    "Thing",
    "Title",
    "Total",
    "Touch",
    "Tower",
    "Track",
    "Trade",
    "Train",
    "Trend",
    "Trial",
    "Trust",
    "Truth",
    "Uncle",
    "Union",
    "Unity",
    "Value",
    "Video",
    "Visit",
    "Voice",
    "Waste",
    "Watch",
    "Water",
    "While",
    "White",
    "Whole",
    "Woman",
    "World",
    "Youth",
    "There",
    "Where",
    "Which",
    "Whose",
    "Whoso",
    "Yours",
    "Yours",
    "Admit",
    "Adopt",
    "Agree",
    "Allow",
    "Alter",
    "Apply",
    "Argue",
    "Arise",
    "Avoid",
    "Begin",
    "Blame",
    "Break",
    "Bring",
    "Build",
    "Burst",
    "Carry",
    "Catch",
    "Cause",
    "Check",
    "Claim",
    "Clean",
    "Clear",
    "Climb",
    "Close",
    "Count",
    "Cover",
    "Cross",
    "Dance",
    "Doubt",
    "Drink",
    "Drive",
    "Enjoy",
    "Enter",
    "Exist",
    "Fight",
    "Focus",
    "Force",
    "Guess",
    "Imply",
    "Issue",
    "Judge",
    "Laugh",
    "Learn",
    "Leave",
    "Limit",
    "Marry",
    "Match",
    "Occur",
    "Offer",
    "Order",
    "Phone",
    "Place",
    "Point",
    "Press",
    "Prove",
    "Raise",
    "Reach",
    "Refer",
    "Relax",
    "Serve",
    "Shall",
    "Share",
    "Shift",
    "Shoot",
    "Sleep",
    "Solve",
    "Sound",
    "Speak",
    "Spend",
    "Split",
    "Stand",
    "Start",
    "State",
    "Stick",
    "Study",
    "Teach",
    "Thank",
    "Think",
    "Throw",
    "Train",
    "Treat",
    "Trust",
    "Visit",
    "Voice",
    "Waste",
    "Watch",
    "Worry",
    "Would",
    "Write",
    "Above",
    "Acute",
    "Alive",
    "Alone",
    "Angry",
    "Aware",
    "Awful",
    "Basic",
    "Black",
    "Blind",
    "Brave",
    "Brief",
    "Broad",
    "Brown",
    "Cheap",
    "Chief",
    "Civil",
    "Clean",
    "Clear",
    "Close",
    "Crazy",
    "Daily",
    "Dirty",
    "Early",
    "Empty",
    "Equal",
    "Exact",
    "Extra",
    "Faint",
    "False",
    "Fifth",
    "Final",
    "First",
    "Fresh",
    "Front",
    "Funny",
    "Giant",
    "Grand",
    "Great",
    "Green",
    "Gross",
    "Happy",
    "Harsh",
    "Heavy",
    "Human",
    "Ideal",
    "Inner",
    "Joint",
    "Large",
    "Legal",
    "Level",
    "Light",
    "Local",
    "Loose",
    "Lucky",
    "Magic",
    "Major",
    "Minor",
    "Moral",
    "Naked",
    "Nasty",
    "Naval",
    "Other",
    "Outer",
    "Plain",
    "Prime",
    "Prior",
    "Proud",
    "Quick",
    "Quiet",
    "Rapid",
    "Ready",
    "Right",
    "Roman",
    "Rough",
    "Round",
    "Royal",
    "Rural",
    "Sharp",
    "Sheer",
    "Short",
    "Silly",
    "Sixth",
    "Small",
    "Smart",
    "Solid",
    "Sorry",
    "Spare",
    "Steep",
    "Still",
    "Super",
    "Sweet",
    "Thick",
    "Third",
    "Tight",
    "Total",
    "Tough",
    "Upper",
    "Upset",
    "Urban",
    "Usual",
    "Vague",
    "Valid",
    "Vital",
    "White",
    "Whole",
    "Wrong",
    "Young",
    "Afore",
    "After",
    "Bothe",
    "Other",
    "Since",
    "Slash",
    "Until",
    "Where",
    "While",
    "About",
    "Above",
    "Adown",
    "Afore",
    "After",
    "Along",
    "Aloof",
    "Among",
    "Below",
    "Circa",
    "Cross",
    "Furth",
    "Minus",
    "Neath",
    "Round",
    "Since",
    "Spite",
    "Under",
    "Until",
    "Marry",
    "Mercy",
    "Night",
    "Havoc",
    "Hella",
    "Hello",
]
const words = word.map(element => {
    return element.toLowerCase()
})

//  const charArray = word.map(el => {
//      return el.split('')
//  })
const charArray = word.map(el => {
    return word.join('')
})
//  console.log(charArray)
let trie = 0

const game = document.querySelector(".game")
const overlay = document.querySelector(".overlay")
const buttonp = document.querySelector(".buttonp")
const submit = document.querySelector(".submit")
const header = document.querySelector(".header")
const tries = document.querySelectorAll(".tries")
const body = document.querySelector("body")
const background = document.querySelector(".background")


let secretWord = words[Math.floor(Math.random() * words.length)]
let swChar = Array.from(secretWord)
 console.log(secretWord)
// console.log(swChar)

//crear funcion para rellenar input 



const openGame = () => {
    game.classList.remove("hidden")
    overlay.classList.add("hidden")
    submit.classList.remove("hidden")
    header.classList.add("hidden")
    background.classList.remove("hidden")
}



submit.addEventListener("click", () => {
    let guessWord = []
    let correct = true
    const guess = tries[trie].querySelectorAll("input")
    const pruebas = tries[trie].querySelectorAll("div")
    

    guess.forEach(el => {                    // guess word
        guessWord.push(el.value)
     })


    let completeGuess = guessWord.join('')
    // console.log(guessWord.join(''))
    // console.log(guessWord)
    console.log(completeGuess)

    if (completeGuess.length < 5 || !words.includes(completeGuess)){       // cannot click less than 5 words nor words that arrent on the array
        return
    }
    
    
    for (let i = 0; i < 5; i++){           // change box color
        if (guessWord[i] === swChar[i]){
            pruebas[i].classList.add("green")
         } else if (swChar.includes(guessWord[i])){
            pruebas[i].classList.add("yellow")
            correct = false
         } else {
            pruebas[i].classList.add("gray")
            correct = false
        }
    } 
    if (correct){
        body.classList.add("victory")
        submit.classList.add("hidden")
        background.classList.add("hidden")
    } else {
        trie++
        const divs = tries[trie].querySelectorAll("div")
        divs.forEach((div) => {
            div.innerHTML = '<input  type="text" maxlength="1"/>'
        })
        tries[trie].classList.remove("hidden")
    }

    console.log(trie)

     if (trie === 5){
        body.classList.add("defeat")
        background.classList.add("hidden")

     }


})

// const endGame = () => {
//     if (trie = 6){
//         body.classList.add("defeat")    
//     }
// }
// console.log(trie)

buttonp.addEventListener("click", () => {
    openGame()
})
